line_processor: line_processor.o
	gcc --std=gnu99 -o line_processor line_processor.o

line_processor.o: line_processor.c
	gcc --std=gnu99 -c line_processor.c

clean: 
	rm line_processor.o line_processor