movies_by_year: movies_by_year.o
	gcc --std=gnu99 -o movies_by_year movies_by_year.o

movies_by_year.o: movies_by_year.c
	gcc --std=gnu99 -c movies_by_year.c

clean: 
	rm movies_by_year.o movies_by_year